### ISSUE TITLE
Can a compiled version of RM4 be released？

### ISSUE THREAD

**Issue by CatzTimes** [EvolutionPlugins/Dummy#32]
When I tried to compile, I encountered a problem that I couldn't solve, so I asked you to publish a RM4 compiled version of the plugin.
@DiFFoZ @archie426

**Comment by DiFFoZ** [comment]
Sure
https://github.com/EvolutionPlugins/Dummy/releases/tag/0.0.0
But I didn't test if it works fine.

**Comment by hiilikewiki** [comment]
Why was I pinged lol?
