### ISSUE TITLE
I beg you to make a usable version...

### ISSUE THREAD

**Issue by CatzTimes** [EvolutionPlugins/Dummy#33]
The script 'Dummy.Dummy' could not be instantiated!

I ran into the above problem when I tried to load.
@DiFFoZ

**Comment by DiFFoZ** [comment]
Sorry, but I deprecated Rocket version. Use instead a OpenMod

**Comment by CatzTimes** [comment]
I also want to use OpenMod, but I have a lot of plug-ins here, but I haven’t got the OpenMod version update. I can’t use OpenMod.

**Comment by DiFFoZ** [comment]
You can wait about 5 days when OpenMod releases the 3.0 version? I don't have much time to update Rocket version to the latest Unturned version.

**Comment by CatzTimes** [comment]
Yes, thank you so much!

**Comment by CatzTimes** [comment]
I saw that the 3.0 version of OpenMod has been released, is there any time to make it now?
   From Google Translate.

**Comment by DiFFoZ** [comment]
You could now install OpenMod with RocketMod. So install openmod version and it should work fine!

**Comment by CatzTimes** [comment]
I tried the method you mentioned, but there are a lot of errors, I can't use it...
I sincerely request you to make the latest RM4 version in your spare time.
